2008-02-15  Lillian Angel  <langel@redhat.com>
        * INSTALL: Updated.
        * Makefile.am: Updated patches. Added download target, added extract
        and extract-ecj targets. Removed clone and clone-ecj targets. Updated
        all paths and targets appropriately.
        * Makefile.in: Regenerate.
        * configure: Regenerate.
        * configure.ac: Added new tools: tar, md5sum.
        * gcjwebplugin.cc: Updated for 1.6.0.
        * generated/sun/awt/X11/generator/sizer.32: Regenerated.
        * generated/sun/awt/X11/generator/sizer.32.c: Regenerated.
        * patches/icedtea-ant.patch: Updated.
        * patches/icedtea-bytebuffer-compact.patch: Updated.
        * patches/icedtea-certbundle.patch: Updated.
        * patches/icedtea-copy-plugs.patch: Updated.
        * patches/icedtea-core-build.patch: Updated.
        * patches/icedtea-ecj.patch: Updated.
        * patches/icedtea-gcc-4.3.patch: Updated.
        * patches/icedtea-headers.patch: Updated.
        * patches/icedtea-lib64.patch: Updated.
        * patches/icedtea-libraries.patch: Updated.
        * patches/icedtea-linker-options.patch: Updated.
        * patches/icedtea-memory-limits.patch: Updated.
        * patches/icedtea-plugin.patch: Updated.
        * patches/icedtea-ports.patch: Updated.
        * patches/icedtea-signature-iterator.patch: Updated.
        * patches/icedtea-signed-types.patch: Updated.
        * patches/icedtea-ssl.patch: Updated.
        * patches/icedtea-test-atomic-operations.patch: Updated.
        * patches/icedtea-use-system-tzdata.patch: Updated.
        * patches/icedtea-version.patch: Updated.
        * patches/icedtea-zero.patch: Updated.
        * patches/icedtea-bytecodeInterpreter.patch: Removed.
        * patches/icedtea-bytecodeInterpreterWithChecks.patch: Removed.
        * rt/java/io/PushbackReader.java: Removed.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -706,9 +706,10 @@ am__fastdepCXX_TRUE
 am__fastdepCXX_FALSE
 FIND
 PATCH
-ZIP
-UNZIP
+TAR
 CHMOD
+MD5SUM
+WGET
 FASTJAR
 ac_ct_FASTJAR
 GAWK
@@ -748,7 +749,6 @@ ZERO_BUILD_TRUE
 ZERO_BUILD_FALSE
 CORE_BUILD_TRUE
 CORE_BUILD_FALSE
-MERCURIAL
 CPP
 GREP
 EGREP
@@ -4337,16 +4337,16 @@ echo "$as_me: error: patch program not found in PATH" >&2;}
 
 
 if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}zip", so it can be a program name with args.
-set dummy ${ac_tool_prefix}zip; ac_word=$2
+  # Extract the first word of "${ac_tool_prefix}tar", so it can be a program name with args.
+set dummy ${ac_tool_prefix}tar; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ZIP+set}" = set; then
+if test "${ac_cv_path_TAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $ZIP in
+  case $TAR in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_ZIP="$ZIP" # Let the user override the test with a path.
+  ac_cv_path_TAR="$TAR" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -4356,7 +4356,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ZIP="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_TAR="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4367,10 +4367,10 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-ZIP=$ac_cv_path_ZIP
-if test -n "$ZIP"; then
-  { echo "$as_me:$LINENO: result: $ZIP" >&5
-echo "${ECHO_T}$ZIP" >&6; }
+TAR=$ac_cv_path_TAR
+if test -n "$TAR"; then
+  { echo "$as_me:$LINENO: result: $TAR" >&5
+echo "${ECHO_T}$TAR" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -4378,18 +4378,18 @@ fi
 
 
 fi
-if test -z "$ac_cv_path_ZIP"; then
-  ac_pt_ZIP=$ZIP
-  # Extract the first word of "zip", so it can be a program name with args.
-set dummy zip; ac_word=$2
+if test -z "$ac_cv_path_TAR"; then
+  ac_pt_TAR=$TAR
+  # Extract the first word of "tar", so it can be a program name with args.
+set dummy tar; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ac_pt_ZIP+set}" = set; then
+if test "${ac_cv_path_ac_pt_TAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $ac_pt_ZIP in
+  case $ac_pt_TAR in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_ac_pt_ZIP="$ac_pt_ZIP" # Let the user override the test with a path.
+  ac_cv_path_ac_pt_TAR="$ac_pt_TAR" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -4399,7 +4399,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ac_pt_ZIP="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_ac_pt_TAR="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4410,17 +4410,17 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-ac_pt_ZIP=$ac_cv_path_ac_pt_ZIP
-if test -n "$ac_pt_ZIP"; then
-  { echo "$as_me:$LINENO: result: $ac_pt_ZIP" >&5
-echo "${ECHO_T}$ac_pt_ZIP" >&6; }
+ac_pt_TAR=$ac_cv_path_ac_pt_TAR
+if test -n "$ac_pt_TAR"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_TAR" >&5
+echo "${ECHO_T}$ac_pt_TAR" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
-  if test "x$ac_pt_ZIP" = x; then
-    ZIP=""
+  if test "x$ac_pt_TAR" = x; then
+    TAR=""
   else
     case $cross_compiling:$ac_tool_warned in
 yes:)
@@ -4432,124 +4432,15 @@ whose name does not start with the host triplet.  If you think this
 configuration is useful to you, please write to autoconf@gnu.org." >&2;}
 ac_tool_warned=yes ;;
 esac
-    ZIP=$ac_pt_ZIP
+    TAR=$ac_pt_TAR
   fi
 else
-  ZIP="$ac_cv_path_ZIP"
+  TAR="$ac_cv_path_TAR"
 fi
 
- if test x"$ZIP" = x ; then
-   { { echo "$as_me:$LINENO: error: zip program not found in PATH" >&5
-echo "$as_me: error: zip program not found in PATH" >&2;}
-   { (exit 1); exit 1; }; }
- fi
-
-
-if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}unzip", so it can be a program name with args.
-set dummy ${ac_tool_prefix}unzip; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_UNZIP+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $UNZIP in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_UNZIP="$UNZIP" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_UNZIP="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-UNZIP=$ac_cv_path_UNZIP
-if test -n "$UNZIP"; then
-  { echo "$as_me:$LINENO: result: $UNZIP" >&5
-echo "${ECHO_T}$UNZIP" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-fi
-if test -z "$ac_cv_path_UNZIP"; then
-  ac_pt_UNZIP=$UNZIP
-  # Extract the first word of "unzip", so it can be a program name with args.
-set dummy unzip; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ac_pt_UNZIP+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $ac_pt_UNZIP in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_ac_pt_UNZIP="$ac_pt_UNZIP" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ac_pt_UNZIP="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-ac_pt_UNZIP=$ac_cv_path_ac_pt_UNZIP
-if test -n "$ac_pt_UNZIP"; then
-  { echo "$as_me:$LINENO: result: $ac_pt_UNZIP" >&5
-echo "${ECHO_T}$ac_pt_UNZIP" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-  if test "x$ac_pt_UNZIP" = x; then
-    UNZIP=""
-  else
-    case $cross_compiling:$ac_tool_warned in
-yes:)
-{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&5
-echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&2;}
-ac_tool_warned=yes ;;
-esac
-    UNZIP=$ac_pt_UNZIP
-  fi
-else
-  UNZIP="$ac_cv_path_UNZIP"
-fi
-
- if test x"$UNZIP" = x ; then
-   { { echo "$as_me:$LINENO: error: unzip program not found in PATH" >&5
-echo "$as_me: error: unzip program not found in PATH" >&2;}
+ if test x"$TAR" = x ; then
+   { { echo "$as_me:$LINENO: error: tar program not found in PATH" >&5
+echo "$as_me: error: tar program not found in PATH" >&2;}
    { (exit 1); exit 1; }; }
  fi
 
@@ -4659,6 +4550,224 @@ fi
  if test x"$CHMOD" = x ; then
    { { echo "$as_me:$LINENO: error: chmod program not found in PATH" >&5
 echo "$as_me: error: chmod program not found in PATH" >&2;}
+   { (exit 1); exit 1; }; }
+ fi
+
+
+if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}md5sum", so it can be a program name with args.
+set dummy ${ac_tool_prefix}md5sum; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_MD5SUM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MD5SUM in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MD5SUM="$MD5SUM" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_MD5SUM="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+MD5SUM=$ac_cv_path_MD5SUM
+if test -n "$MD5SUM"; then
+  { echo "$as_me:$LINENO: result: $MD5SUM" >&5
+echo "${ECHO_T}$MD5SUM" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_MD5SUM"; then
+  ac_pt_MD5SUM=$MD5SUM
+  # Extract the first word of "md5sum", so it can be a program name with args.
+set dummy md5sum; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_MD5SUM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_MD5SUM in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_MD5SUM="$ac_pt_MD5SUM" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_MD5SUM="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_MD5SUM=$ac_cv_path_ac_pt_MD5SUM
+if test -n "$ac_pt_MD5SUM"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_MD5SUM" >&5
+echo "${ECHO_T}$ac_pt_MD5SUM" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_MD5SUM" = x; then
+    MD5SUM=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    MD5SUM=$ac_pt_MD5SUM
+  fi
+else
+  MD5SUM="$ac_cv_path_MD5SUM"
+fi
+
+ if test x"$MD5SUM" = x ; then
+   { { echo "$as_me:$LINENO: error: md5sum program not found in PATH" >&5
+echo "$as_me: error: md5sum program not found in PATH" >&2;}
+   { (exit 1); exit 1; }; }
+ fi
+
+
+if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}wget", so it can be a program name with args.
+set dummy ${ac_tool_prefix}wget; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_WGET+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $WGET in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_WGET="$WGET" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_WGET="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+WGET=$ac_cv_path_WGET
+if test -n "$WGET"; then
+  { echo "$as_me:$LINENO: result: $WGET" >&5
+echo "${ECHO_T}$WGET" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_WGET"; then
+  ac_pt_WGET=$WGET
+  # Extract the first word of "wget", so it can be a program name with args.
+set dummy wget; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_WGET+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_WGET in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_WGET="$ac_pt_WGET" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_WGET="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_WGET=$ac_cv_path_ac_pt_WGET
+if test -n "$ac_pt_WGET"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_WGET" >&5
+echo "${ECHO_T}$ac_pt_WGET" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_WGET" = x; then
+    WGET=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    WGET=$ac_pt_WGET
+  fi
+else
+  WGET="$ac_cv_path_WGET"
+fi
+
+ if test x"$WGET" = x ; then
+   { { echo "$as_me:$LINENO: error: wget program not found in PATH" >&5
+echo "$as_me: error: wget program not found in PATH" >&2;}
    { (exit 1); exit 1; }; }
  fi
 
@@ -7048,118 +7157,6 @@ fi
     fi
   fi
 
-
-if test "$ALT_OPENJDK_SRC_ZIP" = "not specified"; then
-  if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}hg", so it can be a program name with args.
-set dummy ${ac_tool_prefix}hg; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_MERCURIAL+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $MERCURIAL in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_MERCURIAL="$MERCURIAL" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_MERCURIAL="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-MERCURIAL=$ac_cv_path_MERCURIAL
-if test -n "$MERCURIAL"; then
-  { echo "$as_me:$LINENO: result: $MERCURIAL" >&5
-echo "${ECHO_T}$MERCURIAL" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-fi
-if test -z "$ac_cv_path_MERCURIAL"; then
-  ac_pt_MERCURIAL=$MERCURIAL
-  # Extract the first word of "hg", so it can be a program name with args.
-set dummy hg; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ac_pt_MERCURIAL+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $ac_pt_MERCURIAL in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_ac_pt_MERCURIAL="$ac_pt_MERCURIAL" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ac_pt_MERCURIAL="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-ac_pt_MERCURIAL=$ac_cv_path_ac_pt_MERCURIAL
-if test -n "$ac_pt_MERCURIAL"; then
-  { echo "$as_me:$LINENO: result: $ac_pt_MERCURIAL" >&5
-echo "${ECHO_T}$ac_pt_MERCURIAL" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-  if test "x$ac_pt_MERCURIAL" = x; then
-    MERCURIAL=""
-  else
-    case $cross_compiling:$ac_tool_warned in
-yes:)
-{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&5
-echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&2;}
-ac_tool_warned=yes ;;
-esac
-    MERCURIAL=$ac_pt_MERCURIAL
-  fi
-else
-  MERCURIAL="$ac_cv_path_MERCURIAL"
-fi
-
- if test x"$MERCURIAL" = x ; then
-   { { echo "$as_me:$LINENO: error: hg program not found in PATH" >&5
-echo "$as_me: error: hg program not found in PATH" >&2;}
-   { (exit 1); exit 1; }; }
- fi
-
-
-fi
 
 
 ac_ext=c
@@ -10873,12 +10870,12 @@ am__fastdepCXX_TRUE!$am__fastdepCXX_TRUE$ac_delim
 am__fastdepCXX_FALSE!$am__fastdepCXX_FALSE$ac_delim
 FIND!$FIND$ac_delim
 PATCH!$PATCH$ac_delim
-ZIP!$ZIP$ac_delim
-UNZIP!$UNZIP$ac_delim
+TAR!$TAR$ac_delim
 CHMOD!$CHMOD$ac_delim
+MD5SUM!$MD5SUM$ac_delim
+WGET!$WGET$ac_delim
 FASTJAR!$FASTJAR$ac_delim
 ac_ct_FASTJAR!$ac_ct_FASTJAR$ac_delim
-GAWK!$GAWK$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -10920,6 +10917,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+GAWK!$GAWK$ac_delim
 SYSTEM_GCJ_DIR!$SYSTEM_GCJ_DIR$ac_delim
 SYSTEM_ICEDTEA_DIR!$SYSTEM_ICEDTEA_DIR$ac_delim
 SYSTEM_ANT_DIR!$SYSTEM_ANT_DIR$ac_delim
@@ -10956,7 +10954,6 @@ ZERO_BUILD_TRUE!$ZERO_BUILD_TRUE$ac_delim
 ZERO_BUILD_FALSE!$ZERO_BUILD_FALSE$ac_delim
 CORE_BUILD_TRUE!$CORE_BUILD_TRUE$ac_delim
 CORE_BUILD_FALSE!$CORE_BUILD_FALSE$ac_delim
-MERCURIAL!$MERCURIAL$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
