2008-02-05  Lillian Angel  <langel@redhat.com>
        * Makefile.am: Only apply patches/icedtea-gcc-4.3.patch if
        libgcj-4.3.0.jar is installed.
        * Makefile.in: Regenerate.
        * acinclude.m4: If libgcj-4.3*.jar is not found, then search for
        libgcj-4.1*.jar and set LIBGCJ_OLD.
        * configure: Regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -727,7 +727,10 @@ JAR
 RMIC
 ECJ
 ECJ_JAR
+LIBGCJ_OLD_TRUE
+LIBGCJ_OLD_FALSE
 LIBGCJ_JAR
+LIBGCJ_OLD
 XALAN2_JAR
 XALAN2_SERIALIZER_JAR
 XERCES2_JAR
@@ -1374,7 +1377,7 @@ Optional Packages:
   --with-jar              specify location of the jar
   --with-rmic             specify location of the rmic
   --with-ecj-jar          specify location of the ECJ jar
-  --with-libgcj-jar       specify location of the libgcj jar
+  --with-libgcj-jar       specify location of the libgcj 4.3.0 jar
   --with-xalan2-jar       specify location of the xalan2 jar
   --with-xalan2-serializer-jar
                           specify location of the xalan2-serializer jar
@@ -6575,8 +6578,16 @@ else
 fi
 
   if test -z "${LIBGCJ_JAR}"; then
-    { echo "$as_me:$LINENO: checking for libgcj-4.1.2.jar" >&5
-echo $ECHO_N "checking for libgcj-4.1.2.jar... $ECHO_C" >&6; }
+     if test x != x; then
+  LIBGCJ_OLD_TRUE=
+  LIBGCJ_OLD_FALSE='#'
+else
+  LIBGCJ_OLD_TRUE='#'
+  LIBGCJ_OLD_FALSE=
+fi
+
+    { echo "$as_me:$LINENO: checking for libgcj-4.3.0.jar or lib-4.1.2.jar" >&5
+echo $ECHO_N "checking for libgcj-4.3.0.jar or lib-4.1.2.jar... $ECHO_C" >&6; }
     if test -e "/usr/share/java/libgcj-4.3.0.jar"; then
       LIBGCJ_JAR=/usr/share/java/libgcj-4.3.0.jar
       { echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
@@ -6587,8 +6598,28 @@ echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
 	{ echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
 echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
       else
-        { echo "$as_me:$LINENO: result: no" >&5
+	 if test x = x; then
+  LIBGCJ_OLD_TRUE=
+  LIBGCJ_OLD_FALSE='#'
+else
+  LIBGCJ_OLD_TRUE='#'
+  LIBGCJ_OLD_FALSE=
+fi
+
+        if test -e "/usr/share/java/libgcj-4.1.2.jar"; then
+          LIBGCJ_JAR=/usr/share/java/libgcj-4.1.2.jar
+          { echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
+echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
+	else
+	  if test -e "/usr/share/java/libgcj-4.1.jar"; then
+            LIBGCJ_JAR=/usr/share/java/libgcj-4.1.jar
+            { echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
+echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
+	  else
+	    { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+	  fi
+	fi
       fi
     fi
   fi
@@ -6597,6 +6628,7 @@ echo "${ECHO_T}no" >&6; }
 echo "$as_me: error: \"A LIBGCJ jar was not found.\"" >&2;}
    { (exit 1); exit 1; }; }
   fi
+
 
 
 
@@ -10125,6 +10157,20 @@ echo "$as_me: error: conditional \"WITH_ICEDTEA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${LIBGCJ_OLD_TRUE}" && test -z "${LIBGCJ_OLD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LIBGCJ_OLD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LIBGCJ_OLD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LIBGCJ_OLD_TRUE}" && test -z "${LIBGCJ_OLD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LIBGCJ_OLD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LIBGCJ_OLD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${USE_ALT_OPENJDK_SRC_ZIP_TRUE}" && test -z "${USE_ALT_OPENJDK_SRC_ZIP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USE_ALT_OPENJDK_SRC_ZIP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -10830,7 +10876,10 @@ JAR!$JAR$ac_delim
 RMIC!$RMIC$ac_delim
 ECJ!$ECJ$ac_delim
 ECJ_JAR!$ECJ_JAR$ac_delim
+LIBGCJ_OLD_TRUE!$LIBGCJ_OLD_TRUE$ac_delim
+LIBGCJ_OLD_FALSE!$LIBGCJ_OLD_FALSE$ac_delim
 LIBGCJ_JAR!$LIBGCJ_JAR$ac_delim
+LIBGCJ_OLD!$LIBGCJ_OLD$ac_delim
 XALAN2_JAR!$XALAN2_JAR$ac_delim
 XALAN2_SERIALIZER_JAR!$XALAN2_SERIALIZER_JAR$ac_delim
 XERCES2_JAR!$XERCES2_JAR$ac_delim
@@ -10858,7 +10907,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
