2008-02-27  Joshua Sumali  <jsumali@redhat.com>             Francis Kung  <fkung@redhat.com>
        * Makefile.am:
        (tools.stamp): Removed since NetX sources moved from tools/ to rt/
        (tools): Likewise.
        (tools-source-files.txt): Likewise.
        (tools-class-files.stamp): Likewise.
        (clean-tools): Likewise.
        (default-jnlp.stamp): New target.
        (default-jnlp): Likewise.
        (rt-closed.jar): Add rt/net when creating jar.
        (ICEDTEA_PATCHES): Add NETX_PLUGIN conditional.
        * Makefile.in: Regeneraged.
        * acinclude.m4: (ENABLE_NETX_PLUGIN): New macro
        * configure: Regenerated.
        * configure.ac: Add ENABLE_NETX_PLUGIN.
        * README: Updated.
        * patches/icedtea-copy-plugs.patch: Added importing of rt/net/* as binary
        plugs to rt.jar.
        * patches/icedtea-netx-plugin.patch: New file. This patch is used when
        NETX_PLUGIN is true.
        * patches/icedtea-webservices.patch: New file. This is
        icedtea-jnlp-launcher.patch and icedtea-plugin.patch combined into one.
        * patches/icedtea-jnlp-launcher.patch: Removed.
        * patches/icedtea-plugin.patch: Removed.
        * tools/: This former directory for holding NetX sources was deleted and the
        sources were moved to ...
        * rt/net/sourceforge/: Here. NetX sources now follow correct package
        naming.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -746,6 +746,8 @@ FAST_BUILD_TRUE
 FAST_BUILD_FALSE
 ZERO_BUILD_TRUE
 ZERO_BUILD_FALSE
+NETX_PLUGIN_TRUE
+NETX_PLUGIN_FALSE
 CORE_BUILD_TRUE
 CORE_BUILD_FALSE
 MERCURIAL
@@ -1412,6 +1414,8 @@ Optional Features:
   --enable-fast-build     optimize for quick building: use -O0 and do not
                           build documentation
   --enable-zero           use zero-assembler port on non-zero platforms
+  --enable-netx-plugin    enable experimental caching and security support in
+                          applet plugin
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -7016,6 +7020,37 @@ fi
 
 
 
+  # Check whether --enable-netx-plugin was given.
+if test "${enable_netx_plugin+set}" = set; then
+  enableval=$enable_netx_plugin;
+    { echo "$as_me:$LINENO: checking netx plugin" >&5
+echo $ECHO_N "checking netx plugin... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: result: will enable netx plugin" >&5
+echo "${ECHO_T}will enable netx plugin" >&6; }
+     if test x = x; then
+  NETX_PLUGIN_TRUE=
+  NETX_PLUGIN_FALSE='#'
+else
+  NETX_PLUGIN_TRUE='#'
+  NETX_PLUGIN_FALSE=
+fi
+
+
+else
+
+     if test x != x; then
+  NETX_PLUGIN_TRUE=
+  NETX_PLUGIN_FALSE='#'
+else
+  NETX_PLUGIN_TRUE='#'
+  NETX_PLUGIN_FALSE=
+fi
+
+
+fi
+
+
+
   if test "x${ZERO_BUILD_TRUE}" = x; then
      if test x = x; then
   CORE_BUILD_TRUE=
@@ -10575,6 +10610,20 @@ echo "$as_me: error: conditional \"ZERO_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${NETX_PLUGIN_TRUE}" && test -z "${NETX_PLUGIN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NETX_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NETX_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${NETX_PLUGIN_TRUE}" && test -z "${NETX_PLUGIN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NETX_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NETX_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CORE_BUILD_TRUE}" && test -z "${CORE_BUILD_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CORE_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -11285,6 +11334,8 @@ FAST_BUILD_TRUE!$FAST_BUILD_TRUE$ac_delim
 FAST_BUILD_FALSE!$FAST_BUILD_FALSE$ac_delim
 ZERO_BUILD_TRUE!$ZERO_BUILD_TRUE$ac_delim
 ZERO_BUILD_FALSE!$ZERO_BUILD_FALSE$ac_delim
+NETX_PLUGIN_TRUE!$NETX_PLUGIN_TRUE$ac_delim
+NETX_PLUGIN_FALSE!$NETX_PLUGIN_FALSE$ac_delim
 CORE_BUILD_TRUE!$CORE_BUILD_TRUE$ac_delim
 CORE_BUILD_FALSE!$CORE_BUILD_FALSE$ac_delim
 MERCURIAL!$MERCURIAL$ac_delim
@@ -11325,7 +11376,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 74; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
