2007-06-21  Kyle Galloway  <kgallowa@redhat.com>
  * acinclude.m4: Added ENABLE_CCACHE option to enable ccache unless it is
  disabled by --disable-ccache, or cannot be found.
  * configure.ac: Use ENABLE_CCACHE macro.
  * Makefile.am: Added conditional ccache patch to ICEDTEA_PATCHES.
  * patches/icedtea-ccache.patch: New file.
  * configure: Regenerated.
  * Makefile.in: Ditto.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -727,6 +727,9 @@ GNU_CLASSLIB_FOUND_TRUE
 GNU_CLASSLIB_FOUND_FALSE
 FAST_BUILD_TRUE
 FAST_BUILD_FALSE
+CCACHE
+USE_CCACHE_TRUE
+USE_CCACHE_FALSE
 CPP
 GREP
 EGREP
@@ -1325,6 +1328,7 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-fast-build     optimize for quick building: use -O0 and do not
                           build documentation
+  --enable-ccache         use ccache to speed up repeated builds
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5375,6 +5379,102 @@ fi
 
 
 
+  # Check whether --enable-ccache was given.
+if test "${enable_ccache+set}" = set; then
+  enableval=$enable_ccache;
+    if test "${enableval}" = yes; then
+      # Extract the first word of "ccache", so it can be a program name with args.
+set dummy ccache; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_CCACHE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CCACHE"; then
+  ac_cv_prog_CCACHE="$CCACHE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_CCACHE="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+CCACHE=$ac_cv_prog_CCACHE
+if test -n "$CCACHE"; then
+  { echo "$as_me:$LINENO: result: $CCACHE" >&5
+echo "${ECHO_T}$CCACHE" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    fi;
+
+else
+
+      # Extract the first word of "ccache", so it can be a program name with args.
+set dummy ccache; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_CCACHE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CCACHE"; then
+  ac_cv_prog_CCACHE="$CCACHE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_CCACHE="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+CCACHE=$ac_cv_prog_CCACHE
+if test -n "$CCACHE"; then
+  { echo "$as_me:$LINENO: result: $CCACHE" >&5
+echo "${ECHO_T}$CCACHE" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+fi
+
+
+   if test -n "${CCACHE}"; then
+  USE_CCACHE_TRUE=
+  USE_CCACHE_FALSE='#'
+else
+  USE_CCACHE_TRUE='#'
+  USE_CCACHE_FALSE=
+fi
+
+
+
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -7105,6 +7205,13 @@ echo "$as_me: error: conditional \"FAST_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_CCACHE_TRUE}" && test -z "${USE_CCACHE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_CCACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_CCACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -7775,6 +7882,9 @@ GNU_CLASSLIB_FOUND_TRUE!$GNU_CLASSLIB_FOUND_TRUE$ac_delim
 GNU_CLASSLIB_FOUND_FALSE!$GNU_CLASSLIB_FOUND_FALSE$ac_delim
 FAST_BUILD_TRUE!$FAST_BUILD_TRUE$ac_delim
 FAST_BUILD_FALSE!$FAST_BUILD_FALSE$ac_delim
+CCACHE!$CCACHE$ac_delim
+USE_CCACHE_TRUE!$USE_CCACHE_TRUE$ac_delim
+USE_CCACHE_FALSE!$USE_CCACHE_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -7782,7 +7892,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
