2008-02-05  Bernhard Rosenkränzer  <bero@arklinux.org>
        * configure.ac: Added check for jar. If fastjar is not found, then jar
        is used.
        * configure: Regenerate.
        * patches/icedtea-gcc-4.3.patch: New patch for gcc 4.3.

2008-02-05  Lillian Angel  <langel@redhat.com>

        Fixes Bug #96
        * Makefile.am
        (clean-tools): Added clean-hotspot-tools to dependencies.
        (ICEDTEA_PATCHES): Added gcc 4.3 patches.
        (INSTALL): Updated for libgcj-4.3.0.
        * Makefile.in: Regenerate.
        * acinclude.m4: Updated for libgcj-4.3.0.jar.
        * AUTHORS: Added Bernhard Rosenkränzer.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -710,6 +710,7 @@ ZIP
 UNZIP
 CHMOD
 FASTJAR
+ac_ct_FASTJAR
 GAWK
 SYSTEM_GCJ_DIR
 SYSTEM_ICEDTEA_DIR
@@ -4597,26 +4598,26 @@ echo "$as_me: error: chmod program not found in PATH" >&2;}
 
 
 if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}fastjar", so it can be a program name with args.
-set dummy ${ac_tool_prefix}fastjar; ac_word=$2
+  for ac_prog in fastjar jar
+  do
+    # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
+set dummy $ac_tool_prefix$ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_FASTJAR+set}" = set; then
+if test "${ac_cv_prog_FASTJAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $FASTJAR in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_FASTJAR="$FASTJAR" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$FASTJAR"; then
+  ac_cv_prog_FASTJAR="$FASTJAR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_FASTJAR="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_FASTJAR="$ac_tool_prefix$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4624,10 +4625,9 @@ done
 done
 IFS=$as_save_IFS
 
-  ;;
-esac
 fi
-FASTJAR=$ac_cv_path_FASTJAR
+fi
+FASTJAR=$ac_cv_prog_FASTJAR
 if test -n "$FASTJAR"; then
   { echo "$as_me:$LINENO: result: $FASTJAR" >&5
 echo "${ECHO_T}$FASTJAR" >&6; }
@@ -4637,29 +4637,31 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+    test -n "$FASTJAR" && break
+  done
 fi
-if test -z "$ac_cv_path_FASTJAR"; then
-  ac_pt_FASTJAR=$FASTJAR
-  # Extract the first word of "fastjar", so it can be a program name with args.
-set dummy fastjar; ac_word=$2
+if test -z "$FASTJAR"; then
+  ac_ct_FASTJAR=$FASTJAR
+  for ac_prog in fastjar jar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ac_pt_FASTJAR+set}" = set; then
+if test "${ac_cv_prog_ac_ct_FASTJAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $ac_pt_FASTJAR in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_ac_pt_FASTJAR="$ac_pt_FASTJAR" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$ac_ct_FASTJAR"; then
+  ac_cv_prog_ac_ct_FASTJAR="$ac_ct_FASTJAR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ac_pt_FASTJAR="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_ac_ct_FASTJAR="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4667,19 +4669,22 @@ done
 done
 IFS=$as_save_IFS
 
-  ;;
-esac
 fi
-ac_pt_FASTJAR=$ac_cv_path_ac_pt_FASTJAR
-if test -n "$ac_pt_FASTJAR"; then
-  { echo "$as_me:$LINENO: result: $ac_pt_FASTJAR" >&5
-echo "${ECHO_T}$ac_pt_FASTJAR" >&6; }
+fi
+ac_ct_FASTJAR=$ac_cv_prog_ac_ct_FASTJAR
+if test -n "$ac_ct_FASTJAR"; then
+  { echo "$as_me:$LINENO: result: $ac_ct_FASTJAR" >&5
+echo "${ECHO_T}$ac_ct_FASTJAR" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
-  if test "x$ac_pt_FASTJAR" = x; then
+
+  test -n "$ac_ct_FASTJAR" && break
+done
+
+  if test "x$ac_ct_FASTJAR" = x; then
     FASTJAR=""
   else
     case $cross_compiling:$ac_tool_warned in
@@ -4692,18 +4697,15 @@ whose name does not start with the host triplet.  If you think this
 configuration is useful to you, please write to autoconf@gnu.org." >&2;}
 ac_tool_warned=yes ;;
 esac
-    FASTJAR=$ac_pt_FASTJAR
+    FASTJAR=$ac_ct_FASTJAR
   fi
-else
-  FASTJAR="$ac_cv_path_FASTJAR"
 fi
 
- if test x"$FASTJAR" = x ; then
-   { { echo "$as_me:$LINENO: error: fastjar program not found in PATH" >&5
-echo "$as_me: error: fastjar program not found in PATH" >&2;}
+if test "x$FASTJAR" = x; then
+	{ { echo "$as_me:$LINENO: error: Can't find fastjar or jar" >&5
+echo "$as_me: error: Can't find fastjar or jar" >&2;}
    { (exit 1); exit 1; }; }
- fi
-
+fi
 
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}gawk", so it can be a program name with args.
@@ -6579,13 +6581,13 @@ fi
   if test -z "${LIBGCJ_JAR}"; then
     { echo "$as_me:$LINENO: checking for libgcj-4.1.2.jar" >&5
 echo $ECHO_N "checking for libgcj-4.1.2.jar... $ECHO_C" >&6; }
-    if test -e "/usr/share/java/libgcj-4.1.2.jar"; then
-      LIBGCJ_JAR=/usr/share/java/libgcj-4.1.2.jar
+    if test -e "/usr/share/java/libgcj-4.3.0.jar"; then
+      LIBGCJ_JAR=/usr/share/java/libgcj-4.3.0.jar
       { echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
 echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
     else
-      if test -e "/usr/share/java/libgcj-4.1.jar"; then
-        LIBGCJ_JAR=/usr/share/java/libgcj-4.1.jar
+      if test -e "/usr/share/java/libgcj-4.3.jar"; then
+        LIBGCJ_JAR=/usr/share/java/libgcj-4.3.jar
 	{ echo "$as_me:$LINENO: result: ${LIBGCJ_JAR}" >&5
 echo "${ECHO_T}${LIBGCJ_JAR}" >&6; }
       else
@@ -10819,8 +10821,8 @@ ZIP!$ZIP$ac_delim
 UNZIP!$UNZIP$ac_delim
 CHMOD!$CHMOD$ac_delim
 FASTJAR!$FASTJAR$ac_delim
+ac_ct_FASTJAR!$ac_ct_FASTJAR$ac_delim
 GAWK!$GAWK$ac_delim
-SYSTEM_GCJ_DIR!$SYSTEM_GCJ_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -10862,6 +10864,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+SYSTEM_GCJ_DIR!$SYSTEM_GCJ_DIR$ac_delim
 SYSTEM_ICEDTEA_DIR!$SYSTEM_ICEDTEA_DIR$ac_delim
 SYSTEM_ANT_DIR!$SYSTEM_ANT_DIR$ac_delim
 ENABLE_PLUGIN!$ENABLE_PLUGIN$ac_delim
