PR1119: Only add classes to rt-source-files.txt if the class (or one or more of its methods/fields) are actually missing from the boot JDK
2012-08-16  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	* Makefile.am:
	(ICEDTEA_BOOTSTRAP_CLASSES): Only add
	BasicDirectoryModel if addPropertyListener
	is missing.  Dispense with LACKS_SUN_AWT_TOOLKIT
	conditional.
	(rt-source-files.txt): Remove dead ICEDTEA_BOOTSTRAP_DIRS
	which has not been set for some time.
	(rt-class-files.stamp): Replace LACKS_SUN_AWT_TOOLKIT
	conditional with test of contents of ICEDTEA_BOOTSTRAP_CLASSES.
	Note; need to use grep as field contains whitespace.
	(rt.stamp): Likewise.
	* configure.ac:
	Add call to IT_CHECK_FOR_METHOD to look for
	javax.swing.plaf.basic.BasicDirectoryModel.addPropertyChangeListener.
	Improve readability using line breaks.
	* NEWS: Updated.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -101,12 +101,6 @@ SOURCEPATH_DIRS = $(abs_top_srcdir)/generated:$(OPENJDK_SOURCEPATH_DIRS)
 # Sources used from OpenJDK.
 ICEDTEA_BOOTSTRAP_CLASSES =
 
-if LACKS_SUN_AWT_TOOLKIT
-#PR42003 - Missing javax.swing.plaf.basic.BasicDirectoryModel methods cause OpenJDK build failure 
-ICEDTEA_BOOTSTRAP_CLASSES += \
-	$(SHARE)/javax/swing/plaf/basic/BasicDirectoryModel.java
-endif
-
 #PR43148 - javac fails due to missing java.util.regex.Matcher.quoteReplacement
 if LACKS_JAVA_UTIL_REGEX_MATCHER_QUOTEREPLACEMENT
 ICEDTEA_BOOTSTRAP_CLASSES += \
@@ -123,6 +117,12 @@ endif
 if LACKS_JAVAX_MANAGEMENT_MODELMBEAN_MODELMBEANINFO
 ICEDTEA_BOOTSTRAP_CLASSES += \
 	$(SHARE)/javax/management/modelmbean/ModelMBeanInfo.java
+endif
+
+#PR42003 - Missing javax.swing.plaf.basic.BasicDirectoryModel methods cause OpenJDK build failure 
+if LACKS_JAVAX_SWING_PLAF_BASIC_BASICDIRECTORYMODEL_ADDPROPERTYCHANGELISTENER
+ICEDTEA_BOOTSTRAP_CLASSES += \
+	$(SHARE)/javax/swing/plaf/basic/BasicDirectoryModel.java
 endif
 
 # Settings for javac
@@ -2368,39 +2368,36 @@ endif
 
 rt-source-files.txt: $(OPENJDK_BOOT_TREE)
 	rm -f $@
-	for dir in $(ICEDTEA_BOOTSTRAP_DIRS) ; \
-	do \
-	$(FIND) $(abs_top_builddir)/$$dir -name '*.java' >> $@; \
-	done
 	for files in $(ICEDTEA_BOOTSTRAP_CLASSES) ; \
 	do \
 	  echo $$files >> $@ ; \
 	done
+	touch $@
 
 stamps/rt-class-files.stamp: $(INITIAL_BOOTSTRAP_LINK_STAMP) rt-source-files.txt
 	mkdir -p lib/rt
-if LACKS_SUN_AWT_TOOLKIT
-	$(BOOT_DIR)/bin/javac $(IT_JAVACFLAGS) -d lib/rt \
-	  -classpath $(SYSTEM_JDK_DIR)/jre/lib/rt.jar \
-          -sourcepath '$(SOURCEPATH_DIRS)' \
-          -bootclasspath \'\' @rt-source-files.txt ;
-endif
+	if echo $(ICEDTEA_BOOTSTRAP_CLASSES) | grep '\S' &> /dev/null ; then \
+	  $(BOOT_DIR)/bin/javac $(IT_JAVACFLAGS) -d lib/rt \
+	    -classpath $(SYSTEM_JDK_DIR)/jre/lib/rt.jar \
+            -sourcepath '$(SOURCEPATH_DIRS)' \
+            -bootclasspath \'\' @rt-source-files.txt ; \
+	fi
 	mkdir -p stamps
 	touch $@
 
 stamps/rt.stamp: stamps/rt-class-files.stamp
-if LACKS_SUN_AWT_TOOLKIT
-	(set -e ; \
-	 cd lib/rt ; \
-	 for dirs in $(ICEDTEA_BOOTSTRAP_RESOURCES) ; \
-	   do \
-	   destpath=`echo $$dirs|sed -e 's#$(LANGTOOLS)/##' -e 's#$(SHARE)/##'` ; \
-	   mkdir -p `dirname $$destpath` ; \
-	   cp -a ../../$$dirs $$destpath ; \
-	 done ; \
-	 $(ZIP) -qur $(STAGE1_BOOT_DIR)/jre/lib/rt.jar \
-	 com java javax sun );
-endif
+	if echo $(ICEDTEA_BOOTSTRAP_CLASSES) | grep '\S' &> /dev/null ; then \
+	  (set -e ; \
+	   cd lib/rt ; \
+	   for dirs in $(ICEDTEA_BOOTSTRAP_RESOURCES) ; \
+	     do \
+	     destpath=`echo $$dirs|sed -e 's#$(LANGTOOLS)/##' -e 's#$(SHARE)/##'` ; \
+	     mkdir -p `dirname $$destpath` ; \
+	     cp -a ../../$$dirs $$destpath ; \
+	   done ; \
+	   $(ZIP) -qur $(STAGE1_BOOT_DIR)/jre/lib/rt.jar \
+	     com java javax sun ); \
+	fi
 	mkdir -p stamps
 	touch $@
 
