PR3302: zip should be optional, as it's only used in the manually invoked dist-openjdk and dist-openjdk-fsg rules
2017-01-25  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	PR3302: zip should be optional, as it's only used
	in the manually invoked dist-openjdk and
	dist-openjdk-fsg rules
	* Makefile.am:
	(dist-openjdk): Check if ${ZIP} is set and fail
	if not.
	(dist-openjdk-fsg): Likewise.
	* NEWS: Updated.
	* configure.ac:
	Use the non-failing AC_PATH_TOOL macro for zip.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -857,11 +857,17 @@ snapshot: dist
 
 # Creates archive of openjdk.
 dist-openjdk: stamps/extract-cacao.stamp
+	if test "x${ZIP}" = "x"; then \
+	  echo "ERROR: zip not found"; exit 1; \
+	fi
 	find openjdk/ -name \\.hg* | xargs rm -rf	
 	$(ZIP) -r openjdk-$(COMBINED_VERSION) openjdk/
 
 # Creates archive of openjdk that is compliant with Free Software guidelines.
 dist-openjdk-fsg: stamps/patch-fsg.stamp
+	if test "x${ZIP}" = "x"; then \
+	  echo "ERROR: zip not found"; exit 1; \
+	fi
 	$(ZIP) -r openjdk-fsg-$(COMBINED_VERSION) openjdk/
 
 dist-openjdk-fsg-xz: stamps/patch-fsg.stamp
