2007-12-20  Lillian Angel  <langel@redhat.com>
        * Makefile.am: Added checks for ICEDTEA_HOME and SYSTEM_GCJ_DIR.
        * Makefile.in: Regenerate.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -793,7 +793,14 @@ clean-bootstrap-directory:
 stamps/bootstrap-directory-symlink.stamp: $(BOOTSTRAP_DIRECTORY_STAMP)
 	mkdir -p bootstrap
 	rm -f bootstrap/jdk1.6.0
-	ln -sf $(ICEDTEA_HOME) bootstrap/jdk1.6.0
+	if test -d $(ICEDTEA_HOME); \
+	then \
+	  ln -sf $(ICEDTEA_HOME) bootstrap/jdk1.6.0; \
+	else \
+	  echo $(ICEDTEA_HOME) " cannot be found. Try reconfiguring with " \
+	    "--with-icedtea-home=/path/to/java-icedtea-devel"; \
+          exit 1; \
+	fi
 	if ! bootstrap/jdk1.6.0/bin/java -version ; \
          then \
            echo "bootstrap/jdk1.6.0/bin/java" \
@@ -824,15 +831,23 @@ stamps/bootstrap-directory-ecj.stamp:
 	ln -sf $(XALAN2_SERIALIZER_JAR) \
 	  bootstrap/ecj/lib/endorsed/xalan-j2-serializer.jar
 	ln -sf $(XERCES2_JAR) bootstrap/ecj/lib/endorsed/xerces-j2.jar
-	mkdir -p bootstrap/ecj/jre/lib
-	ln -sf $(SYSTEM_GCJ_DIR)/jre/lib/$(INSTALL_ARCH_DIR) bootstrap/ecj/jre/lib/
-	mkdir -p bootstrap/ecj/include
-	for i in $(SYSTEM_GCJ_DIR)/include/*; do \
-	  test -r $$i | continue; \
-	  i=`basename $$i`; \
-	  rm -f bootstrap/ecj/include/$$i; \
-	  ln -s $(SYSTEM_GCJ_DIR)/include/$$i bootstrap/ecj/include/$$i; \
-	done
+	if test -d $(SYSTEM_GCJ_DIR); \
+	then \
+	  mkdir -p bootstrap/ecj/jre/lib; \
+	  ln -sf $(SYSTEM_GCJ_DIR)/jre/lib/$(INSTALL_ARCH_DIR) \
+	    bootstrap/ecj/jre/lib/; \
+	  mkdir -p bootstrap/ecj/include; \
+	  for i in $(SYSTEM_GCJ_DIR)/include/*; do \
+	    test -r $$i | continue; \
+	    i=`basename $$i`; \
+	    rm -f bootstrap/ecj/include/$$i; \
+	    ln -s $(SYSTEM_GCJ_DIR)/include/$$i bootstrap/ecj/include/$$i; \
+	  done; \
+	else \
+	  echo $(SYSTEM_GCJ_DIR) " cannot be found. Try reconfiguring with " \
+	    --with-gcj-home=/path/to/java-gcj-devel ; \
+          exit 1; \
+	fi
 	if test -f bootstrap/jdk1.7.0/jre/lib/tools.jar ; \
 	then \
 		mkdir -p bootstrap/ecj/lib ; \
