Cleanup #07: Remove source/target from javac.in, unset JAVA_HOME and QUIETLY.
2009-08-17  Andrew John Hughes  <ahughes@redhat.com>

	* Makefile.am:
	Add variables for source, target and other
	javac settings so they are standardised across
	the build.  Set JAVA_HOME and JDK_HOME to ""
	to avoid build failures.  Set QUIETLY to ""
	to display HotSpot javac invocations. Remove
	duplicate javac invocations now targets depend
	on INITIAL_BOOTSTRAP_LINK_STAMP.
	* javac.in:
	Remove 1.7 setting.  Add ecj_parms so same
	parameters are used for all ecj invocations.
	* patches/ecj/icedtea-hotspot-default.patch:
	Make SA_CLASSPATH contain the whole CLASSPATH
	and use SA_TOOLS_JAR and SA_RT_JAR for the individual
	files.

diff --git a/patches/ecj/icedtea-hotspot-default.patch b/patches/ecj/icedtea-hotspot-default.patch
--- a/patches/ecj/icedtea-hotspot-default.patch
+++ b/patches/ecj/icedtea-hotspot-default.patch
@@ -1,7 +1,7 @@
 diff -Nru openjdk-ecj.orig/hotspot/make/linux/Makefile openjdk-ecj/hotspot/make/linux/Makefile
---- openjdk-ecj.orig/hotspot/make/linux/Makefile	2008-10-24 10:16:06.000000000 +0100
-+++ openjdk-ecj/hotspot/make/linux/Makefile	2008-10-24 13:32:48.000000000 +0100
-@@ -263,28 +263,24 @@
+--- openjdk-ecj.orig/hotspot/make/linux/Makefile	2009-08-18 17:44:09.000000000 +0100
++++ openjdk-ecj/hotspot/make/linux/Makefile	2009-08-18 18:56:52.000000000 +0100
+@@ -274,28 +274,24 @@
  
  $(TARGETS_C2):  $(SUBDIRS_C2)
  	cd $(OSNAME)_$(BUILDARCH)_compiler2/$@ && $(MAKE) $(MFLAGS)
@@ -31,18 +31,32 @@ diff -Nru openjdk-ecj.orig/hotspot/make/linux/Makefile openjdk-ecj/hotspot/make/
  	cd $(OSNAME)_$(BUILDARCH)_core/$(patsubst %core,%,$@) && $(MAKE) $(MFLAGS) install
  endif
 diff -Nru openjdk-ecj.orig/hotspot/make/linux/makefiles/sa.make openjdk-ecj/hotspot/make/linux/makefiles/sa.make
---- openjdk-ecj.orig/hotspot/make/linux/makefiles/sa.make	2008-10-24 10:16:06.000000000 +0100
-+++ openjdk-ecj/hotspot/make/linux/makefiles/sa.make	2008-10-24 13:32:48.000000000 +0100
-@@ -74,8 +74,8 @@
- 	  mkdir -p $(SA_CLASSDIR);        \
+--- openjdk-ecj.orig/hotspot/make/linux/makefiles/sa.make	2009-08-18 17:35:29.000000000 +0100
++++ openjdk-ecj/hotspot/make/linux/makefiles/sa.make	2009-08-18 19:54:42.000000000 +0100
+@@ -38,7 +38,9 @@
+ GENERATED = $(TOPDIR)/../generated
+ 
+ # tools.jar is needed by the JDI - SA binding
+-SA_CLASSPATH = $(BOOT_JAVA_HOME)/lib/tools.jar
++SA_TOOLS_JAR = $(BOOT_JAVA_HOME)/lib/tools.jar
++SA_RT_JAR = $(BOOT_JAVA_HOME)/jre/lib/rt.jar
++SA_CLASSPATH = $(SA_TOOLS_JAR):$(SA_RT_JAR)
+ 
+ # gnumake 3.78.1 does not accept the *s that
+ # are in AGENT_FILES1 and AGENT_FILES2, so use the shell to expand them
+@@ -65,8 +67,13 @@
+ 	  echo "ALT_BOOTDIR, BOOTDIR or JAVA_HOME needs to be defined to build SA"; \
+ 	  exit 1; \
  	fi
- 
--	$(QUIETLY) $(REMOTE) $(COMPILE.JAVAC) -source 1.4 -classpath $(SA_CLASSPATH) -sourcepath $(AGENT_SRC_DIR) -g -d $(SA_CLASSDIR) $(AGENT_FILES1)
--	$(QUIETLY) $(REMOTE) $(COMPILE.JAVAC) -source 1.4 -classpath $(SA_CLASSPATH) -sourcepath $(AGENT_SRC_DIR) -g -d $(SA_CLASSDIR) $(AGENT_FILES2)
-+	$(QUIETLY) $(REMOTE) $(COMPILE.JAVAC) -source 1.4 -classpath $(SA_CLASSPATH):$(BOOT_JAVA_HOME)/jre/lib/rt.jar -sourcepath $(AGENT_SRC_DIR) -g -d $(SA_CLASSDIR) $(AGENT_FILES1)
-+	$(QUIETLY) $(REMOTE) $(COMPILE.JAVAC) -source 1.4 -classpath $(SA_CLASSPATH):$(BOOT_JAVA_HOME)/jre/lib/rt.jar -sourcepath $(AGENT_SRC_DIR) -g -d $(SA_CLASSDIR) $(AGENT_FILES2)
- 
- 	$(QUIETLY) $(REMOTE) $(COMPILE.RMIC)  -classpath $(SA_CLASSDIR) -d $(SA_CLASSDIR) sun.jvm.hotspot.debugger.remote.RemoteDebuggerServer
- 	$(QUIETLY) echo "$(SA_BUILD_VERSION_PROP)" > $(SA_PROPERTIES)
-
-
+-	$(QUIETLY) if [ ! -f $(SA_CLASSPATH) ] ; then \
+-	  echo "Missing $(SA_CLASSPATH) file. Use 1.6.0 or later version of JDK";\
++	$(QUIETLY) if [ ! -f $(SA_TOOLS_JAR) ] ; then \
++	  echo "Missing $(SA_TOOLS_JAR) file. Use 1.6.0 or later version of JDK";\
++	  echo ""; \
++	  exit 1; \
++	fi
++	$(QUIETLY) if [ ! -f $(SA_RT_JAR) ] ; then \
++	  echo "Missing $(SA_RT_JAR) file. Use 1.6.0 or later version of JDK";\
+ 	  echo ""; \
+ 	  exit 1; \
+ 	fi
